import { defineConfig } from "oxlint";

export default defineConfig({
    plugins: [
        "eslint",
        "import",
        "jsdoc",
        "node",
        "oxc",
        "promise",
        "react",
        "typescript",
        "unicorn",
        "vitest",
    ],
    categories: {
        correctness: "error",
        perf: "error",
    },
    options: {
        typeAware: true,
    },
    env: {
        browser: true,
        node: true,
        vitest: true,
    },
    settings: {
        jsdoc: {
            mode: "typescript",
            tagNamePreference: {
                template: "typeParam",
            },
        },
    },
    rules: {
        curly: "error",
        "getter-return": "error",
        "import/consistent-type-specifier-style": "error",
        "no-array-constructor": "error",
        "no-case-declarations": "error",
        "no-empty": "error",
        "no-empty-function": "error",
        "no-fallthrough": "error",
        "no-prototype-builtins": "error",
        "no-redeclare": "error",
        "no-regex-spaces": "error",
        "no-undef": "error",
        "no-unreachable": "error",
        "no-useless-constructor": "error",
        "react/exhaustive-deps": "error",
        "react/no-array-index-key": "off",
        "react/only-export-components": "error",
        "react/rules-of-hooks": "error",
        "typescript/adjacent-overload-signatures": "error",
        "typescript/ban-ts-comment": "error",
        "typescript/class-literal-property-style": "error",
        "typescript/consistent-type-exports": "error",
        "typescript/consistent-type-imports": "error",
        "typescript/dot-notation": "error",
        "typescript/explicit-function-return-type": "error",
        "typescript/explicit-member-accessibility": "error",
        "typescript/no-confusing-void-expression": "error",
        "typescript/no-explicit-any": ["error", { ignoreRestArgs: true }],
        "typescript/no-inferrable-types": "error",
        "typescript/no-invalid-void-type": "error",
        "typescript/no-misused-promises": "error",
        "typescript/no-require-imports": "error",
        "typescript/no-unnecessary-boolean-literal-compare": "error",
        "typescript/no-unnecessary-condition": "error",
        "typescript/no-unnecessary-template-expression": "error",
        "typescript/no-unnecessary-type-assertion": "error",
        "typescript/no-unnecessary-type-constraint": "error",
        "typescript/no-unnecessary-type-conversion": "error",
        "typescript/no-unnecessary-type-parameters": "error",
        "typescript/no-unsafe-argument": "error",
        "typescript/no-unsafe-assignment": "error",
        "typescript/no-unsafe-call": "error",
        "typescript/no-unsafe-enum-comparison": "error",
        "typescript/no-unsafe-function-type": "error",
        "typescript/no-unsafe-member-access": "error",
        "typescript/no-unsafe-return": "error",
        "typescript/no-useless-default-assignment": "error",
        "typescript/only-throw-error": "error",
        "typescript/prefer-find": "error",
        "typescript/prefer-includes": "error",
        "typescript/prefer-nullish-coalescing": "error",
        "typescript/prefer-optional-chain": "error",
        "typescript/prefer-promise-reject-errors": "error",
        "typescript/prefer-regexp-exec": "error",
        "typescript/promise-function-async": "error",
        "typescript/related-getter-setter-pairs": "error",
        "typescript/require-await": "error",
        "typescript/restrict-plus-operands": "error",
        "typescript/restrict-template-expressions": "off",
        "typescript/return-await": "error",
        "typescript/unified-signatures": "error",
        "unicorn/filename-case": "error",
        "vitest/consistent-test-it": "error",
        "vitest/consistent-vitest-vi": "error",
    },
});
